import { Cormorant_Garamond , Inter } from 'next/font/google';
import "./globals.css";

const cormorantGaramond = Cormorant_Garamond({
  variable: '--font-cormorant-garamond',
  weight: ['400', '700'],  // Add desired weights
  subsets: ['latin'],      // Specify subsets (e.g., 'latin', 'latin-ext')
  display: 'swap',         // Optional: improves loading performance
});
const inter = Inter({
  variable: '--font-inter',
  weight: ['400', '500', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${cormorantGaramond.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
